site_name: Vulkan-hpp-tutorial
repo_url: https://github.com/Mysvac/vulkan-hpp-tutorial

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: material
  - pymdownx.superfences


nav:
  - Home: index.md
  - 简介: md/0000_intro.md
  - 概述: md/0001_overview.md
  - 开发环境: md/0002_env.md
  - 接口差异: md/0003_diff.md
  - 绘制三角形:
    - 设置:
      - 基础代码: md/0100_base.md

