site_name: Vulkan-hpp-tutorial
site_author: 迷枵(Mysvac)
site_url: https://mysvac.github.io/vulkan-hpp-tutorial/
repo_url: https://github.com/Mysvac/vulkan-hpp-tutorial
repo_name: Mysvac/vulkan-hpp-tutorial
site_description: >
  Vulkan 入门教程，使用 C++20 编写，基于官方 Vulkan SDK 的 vulkan-hpp 和 RAII 封装，帮助开发者更现代、安全地学习 Vulkan 图形编程。

theme:
  name: material
  custom_dir: docs/custom
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - custom/css/style.css

nav:
  - 首页: index.md
  - 教程前言: md/00/00_intro.md
  - 开发环境: md/00/01_env.md
  - 接口介绍: md/00/02_diff.md
  - 绘制三角形:
    - 设置:
      - 基础代码: md/01/00_base.md
      - 实例: md/01/01_instance.md
      - 验证层: md/01/02_validation.md
      - 物理设备与队列族: md/01/03_physicaldevice.md
      - 逻辑设备与队列: md/01/04_device.md
    - 呈现:
      - 窗口表面: md/01/10_surface.md
      - 交换链: md/01/11_swapchain.md
      - 图像视图: md/01/12_imageview.md
    - 图形管线基础:
      - 介绍: md/01/20_pipeline.md
      - 着色器: md/01/21_shader.md
      - 固定功能: md/01/22_fixfunction.md
      - 渲染通道: md/01/23_renderpass.md
      - 管线创建: md/01/24_conclusion.md
    - 绘制:
      - 帧缓冲: md/01/30_framebuffer.md
      - 命令缓冲: md/01/31_commandbuffer.md
      - 渲染和呈现: md/01/32_rendering.md
      - 飞行中的帧: md/01/33_flightframe.md
    - 重建交换链: md/01/40_recreateswapchain.md
  - 缓冲与图像:
    - 顶点缓冲:
      - 顶点输入描述: md/02/00_vertexinput.md
      - 创建顶点缓冲: md/02/01_vertexbuffer.md
      - 暂存缓冲: md/02/02_stagingbuffer.md
    - 索引缓冲: md/02/10_indexbuffer.md
    - uniform缓冲: 
      - 描述符布局与缓冲: md/02/20_descriptor1.md
      - 描述符池与集合: md/02/21_descriptor2.md
    - 纹理映射:
      - 纹理图像: md/02/30_texture.md
      - 图像视图和采样器: md/02/31_sampler.md
      - 组合图像采样器: md/02/32_combined.md
    - 深度缓冲: md/02/40_depthbuffer.md
  - 基础功能:
    - 加载模型: md/03/00_loadmodel.md
    - 移动摄像机: md/03/10_movecamera.md
    - 生成Mipmaps: md/03/20_mipmaps.md
    - 多重采样: md/03/30_multisample.md
    - 实例化渲染: md/03/40_instancedrendering.md
    - 推送常量: md/03/50_pushconstant.md
    - 动态uniform: md/03/60_dynamicuniform.md
    - 分离图像与采样器: md/03/70_separatesampler.md
    - 管线缓存: md/03/80_pipelinecache.md
    - 计算着色器与SSBO: md/03/90_compute.md
  - 进阶功能:
    - C++模块化: md/04/00_cxxmodule.md
    - 杂项:
        - 查询池: md/04/10_querypool.md
        - 特化常量: md/04/11_specialization.md
        - TODO: todo.md # pNext 与 sType
        - TODO: todo.md # 新版同步
    - 多管线渲染:
        - 阴影映射: md/04/20_shadowmap.md
        - 延迟渲染: md/04/21_deferred.md
        - TODO: todo.md # 模板测试
        - TODO: todo.md # 延迟渲染
    - 多线程渲染:
      - TODO: todo.md # 资源加载系统
      - TODO: todo.md # 并行命令录制
    - 离屏渲染:
      - TODO: todo.md # 离屏渲染
      - TODO: todo.md # 帧缓冲分离
      - TODO: todo.md # 虚拟纹理
    - 着色器进阶:
      - TODO: todo.md  # 几何着色器
      - TODO: todo.md  # 细分着色器
      - TODO: todo.md # 任务与网格着色器
    - 光线追踪:
      - TODO: todo.md # 加速结构
      - TODO: todo.md # 光追管线
      - TODO: todo.md # 实例化处理
    - 性能优化:
      - TODO: todo.md # 管线屏障
      - TODO: todo.md # 队列并发
      - TODO: todo.md # 稀疏资源
      - TODO: todo.md # 内存分配
    - 高级计算:
      - TODO: todo.md # 共享内存
      - TODO: todo.md # 原子操作
      - TODO: todo.md # 异步计算
      - TODO: todo.md # 子组操作
  - 隐私政策: policy.md
