site_name: Vulkan-hpp-tutorial
site_url: https://mysvac.github.io/vulkan-hpp-tutorial/ 
repo_url: https://github.com/Mysvac/vulkan-hpp-tutorial

theme:
  name: material
  palette:  # 启用深浅模式切换
    - scheme: default  # 浅色模式
      toggle:
        icon: material/weather-sunny  # 太阳图标
        name: 切换到深色模式
    - scheme: slate  # 深色模式（内置）
      toggle:
        icon: material/weather-night  # 月亮图标
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - css/style.css

nav:
  - 首页: index.md
  - 简介: md/0000_intro.md
  - 开发环境: md/0001_env.md
  - 接口差异: md/0002_diff.md
  - 绘制三角形:
    - 设置:
      - 基础代码: md/0100_base.md
      - 实例: md/0101_instance.md
      - 验证层: md/0102_validation.md
      - 物理设备与队列族: md/0103_physicaldevice.md
      - 逻辑设备与队列: md/0104_device.md
    - 呈现:
      - 窗口表面: md/0110_surface.md
      - 交换链: md/0111_swapchain.md
      - 图像视图: md/0112_imageview.md
    - 图像管线基础:
      - 介绍: md/0120_pipeline.md
      - 着色器模块: md/0121_shader.md
      - 固定功能: md/0122_fixfunction.md
      - 渲染通道: md/0123_renderpass.md
