site_name: Vulkan-hpp-tutorial
site_author: 迷枵(Mysvac)
site_url: https://mysvac.github.io/vulkan-hpp-tutorial/
repo_url: https://github.com/Mysvac/vulkan-hpp-tutorial
repo_name: Mysvac/vulkan-hpp-tutorial
site_description: >
  Vulkan 入门教程，使用 C++20 编写，基于官方 Vulkan SDK 的 vulkan-hpp 和 RAII 封装，帮助开发者更现代、安全地学习 Vulkan 图形编程。

theme:
  name: material
  custom_dir: docs/custom
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 教程前言: md/00/00_intro.md
  - 开发环境: md/00/01_env.md
  - 接口介绍: md/00/02_diff.md
  - 绘制三角形:
    - 设置:
      - 基础代码: md/01/00_base.md
      - 实例: md/01/01_instance.md
      - 验证层: md/01/02_validation.md
      - 物理设备与队列族: md/01/03_physicaldevice.md
      - 逻辑设备与队列: md/01/04_device.md
    - 呈现:
      - 窗口表面: md/01/10_surface.md
      - 交换链: md/01/11_swapchain.md
      - 图像视图: md/01/12_imageview.md
      - 渲染通道: md/01/13_renderpass.md
      - 帧缓冲: md/01/14_framebuffer.md
    - 图形管线基础:
      - 介绍: md/01/20_pipeline.md
      - 着色器: md/01/21_shader.md
      - 固定功能: md/01/22_fixfunction.md
      - 管线创建: md/01/23_conclusion.md
    - 绘制:
      - 命令缓冲: md/01/30_commandbuffer.md
      - 渲染和呈现: md/01/31_rendering.md
      - 飞行中的帧: md/01/32_flightframe.md
      - 重建交换链: md/01/33_recreateswapchain.md
  - 缓冲与图像:
    - 顶点缓冲:
      - 顶点输入描述: md/02/00_vertexinput.md
      - 创建顶点缓冲: md/02/01_vertexbuffer.md
      - 暂存缓冲: md/02/02_stagingbuffer.md
    - 索引缓冲: md/02/10_indexbuffer.md
    - uniform缓冲: 
      - 描述符布局与缓冲: md/02/20_descriptor1.md
      - 描述符池与集合: md/02/21_descriptor2.md
    - 纹理映射:
      - 纹理图像: md/02/30_texture.md
      - 图像视图和采样器: md/02/31_sampler.md
      - 组合图像采样器: md/02/32_combined.md
    - 深度缓冲: md/02/40_depthbuffer.md
  - 基础功能:
    - 加载模型: md/03/00_loadmodel.md
    - 移动摄像机: md/03/10_movecamera.md
    - 生成Mipmaps: md/03/20_mipmaps.md
    - 多重采样: md/03/30_multisample.md
    - 实例化渲染: md/03/40_instancedrendering.md
    - 推送常量: md/03/50_pushconstant.md
    - 动态uniform: md/03/60_dynamicuniform.md
    - 分离图像与采样器: md/03/70_separatesampler.md
    - 计算着色器与SSBO: md/03/80_compute.md
  - 进阶功能:
    - C++模块化: md/04/00_cxxmodule.md
    - 特化常量: md/04/10_specialization.md
    - 管线缓存: md/04/11_pipelinecache.md
    - pNext与sType: md/04/12_pnext_stype.md
    - 新版同步: md/04/13_sync2.md
    - 查询池: md/04/14_querypool.md
    - shaderc: md/04/15_shaderc.md
    - 无图像帧缓冲: md/04/20_imageless.md
    - 动态渲染: md/04/21_dynamicrendering.md
    - 其他: md/04/30_other.md
  - 隐私政策: policy.md
