site_name: Vulkan-hpp-tutorial
site_url: https://mysvac.github.io/vulkan-hpp-tutorial/ 
repo_url: https://github.com/Mysvac/vulkan-hpp-tutorial

theme:
  name: material
  palette:  # 启用深浅模式切换
    - scheme: default  # 浅色模式
      toggle:
        icon: material/weather-sunny  # 太阳图标
        name: 切换到深色模式
    - scheme: slate  # 深色模式（内置）
      toggle:
        icon: material/weather-night  # 月亮图标
        name: 切换到浅色模式
  features:
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - css/style.css

nav:
  - 首页: index.md
  - 项目介绍: md/0000_intro.md
  - 开发环境: md/0001_env.md
  - 接口介绍: md/0002_diff.md
  - 绘制三角形:
    - 设置:
      - 基础代码: md/0100_base.md
      - 实例: md/0101_instance.md
      - 验证层: md/0102_validation.md
      - 物理设备与队列族: md/0103_physicaldevice.md
      - 逻辑设备与队列: md/0104_device.md
    - 呈现:
      - 窗口表面: md/0110_surface.md
      - 交换链: md/0111_swapchain.md
      - 图像视图: md/0112_imageview.md
    - 图形管线基础:
      - 介绍: md/0120_pipeline.md
      - 着色器: md/0121_shader.md
      - 固定功能: md/0122_fixfunction.md
      - 渲染通道: md/0123_renderpass.md
      - 结论: md/0124_conclusion.md
    - 绘制:
      - 帧缓冲: md/0130_framebuffer.md
      - 命令缓冲: md/0131_commandbuffer.md
      - 渲染和呈现: md/0132_rendering.md
      - 飞行中的帧: md/0133_flightframe.md
    - 重建交换链: md/0140_recreateswapchain.md
  - 顶点缓冲:
    - 顶点输入描述: md/0200_vertexinput.md
    - 创建顶点缓冲: md/0201_vertexbuffer.md
    - 暂存缓冲: md/0202_stagingbuffer.md
    - 索引缓冲: md/0203_indexbuffer.md
  - uniform缓冲: 
    - 描述符布局与缓冲: md/0300_descriptor1.md
    - 描述符池与集合: md/0301_descriptor2.md
  - 纹理映射:
    - 纹理图像: md/0400_texture.md
    - 图像视图和采样器: md/0401_sampler.md
    - 组合图像采样器: md/0402_combined.md
  - 深度缓冲: md/0500_depthbuffer.md
